# Generated by Django 3.0.14 on 2021-06-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_endorsement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endorsement',
            new_name='Endoresment',
        ),
    ]
