# Generated by Django 3.0.14 on 2021-06-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210621_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='endoresment',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
