# Generated by Django 3.0.14 on 2021-06-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Project',
            new_name='project',
        ),
    ]
