# Generated by Django 3.0.14 on 2021-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='nathi.jpg', null=True, upload_to=''),
        ),
    ]
